# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Assume this is a PR build. If this is a master build, these will be overridden in the first step.
      APP_LOCAL_SANITY_DATASET: rexona-staging-gb
      APP_LOCAL_SITE_URL: https://deploy-preview-${{ github.event.number }}--rexona-web-en-gb-staging.netlify.app
      # Other APP_LOCAL_* env vars would go here
      BUILD_ID: pr-${{ github.event.number }}
      NETLIFY_DEPLOY_ALIAS: deploy-preview-${{ github.event.number }}

    steps:

      - name: Override job environment variables if running on master branch
        if: github.ref == 'refs/heads/master'
        shell: bash
        run: |
          echo "APP_LOCAL_SITE_URL=https://rexona-web-en-gb-staging.netlify.app" >> $GITHUB_ENV
          echo "BUILD_ID=master" >> $GITHUB_ENV
          echo "NETLIFY_DEPLOY_ALIAS=" >> $GITHUB_ENV

      - name: Override job environment variables if running on release branch
        if: /refs\/heads\/(release.*$)/.test(github.ref)
        env:
          BRANCH_NAME: ${{ github.ref.match(/refs\/heads\/(release.*$)/)[1] }}
        shell: bash
        run: |
          echo "APP_LOCAL_SANITY_DATASET=rexona-prod-gb" >> $GITHUB_ENV
          echo "BUILD_ID=${{ env.BRANCH_NAME }}" >> $GITHUB_ENV
          # TODO others

      - uses: actions/checkout@v2
      - name: Build website
        run: echo "Build website here"
      - name: Deploy to staging
        run: echo "Deploy to staging Netlify instance here"
      - name: Run tests
        run: echo "Tests go here"
